apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-multus
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "macvlan-multus",
            "type": "ovn-k8s-cni-overlay",
            "topology":"layer2",
            "subnets": "10.100.200.0/24",
            "mtu": 1300,
            "netAttachDefName": "open5gcore/macvlan-multus",
            "excludeSubnets": "10.100.200.0/29"
          }'
